libgme/game-music-emu

- gme/Ay_Emu.cpp
- gme/Classic_Emu.cpp
- gme/Effects_Buffer.cpp
- gme/Gbs_Emu.cpp
- gme/Gym_Emu.cpp
- gme/Hes_Emu.cpp
- gme/Kss_Emu.cpp
- gme/Nes_Cpu.cpp
- gme/Nes_Vrc6_Apu.cpp
- gme/Nsf_Emu.cpp
- gme/Nsfe_Emu.cpp
- gme/Snes_Spc.cpp
- gme/Spc_Dsp.cpp
- gme/Spc_Emu.cpp
- gme/Vgm_Emu.cpp
- gme/blargg_common.h
The `static_assert()` breaks the build on the MSVC 2015, so, use a condition to use the static_assert at newer MSVC only, and stay with the regular assert on the older MSVC versions.
Original: https://bitbucket.org/mpyne/game-music-emu/pull-requests/38
> Fixed build on the MSVC 2015

- demo/CMakeLists.txt
- demo/basics_multi.c
Similar to `demo`, `demo_multi` writes 10 seconds of audio to `out.wav`, but it sends all even-numbered voices to the left channel and all odd-numbered voices to the right channel.
> Add a multi-channel example

- gme/Ym2612_Nuked.cpp
Fixes https://github.com/libgme/game-music-emu/issues/63
> fix inverted logic in Ym2612_Nuked_Emu::reset()

- gme/Gb_Apu.cpp
From valgrind output:
```
==10374== Conditional jump or move depends on uninitialised value(s)
==10374==    at 0x41B3C8D: int const& std::max<int>(int const&, int const&) (stl_algobase.h:222)
==10374==    by 0x41B32C2: Gb_Apu::update_volume() (Gb_Apu.cpp:83)
==10374==    by 0x41B3C75: Gb_Apu::volume(double) (Gb_Apu.h:87)
==10374==    by 0x41B3144: Gb_Apu::Gb_Apu() (Gb_Apu.cpp:51)
==10374==    by 0x41B5CB1: Gbs_Emu::Gbs_Emu() (Gbs_Emu.cpp:26)
==10374==    by 0x41B5F76: new_gbs_emu() (Gbs_Emu.cpp:100)
==10374==    by 0x41A4A82: gme_internal_new_emu_(gme_type_t_ const*, int, bool) (gme.cpp:227)
==10374==    by 0x41A4BE8: gme_new_emu (gme.cpp:264)
==10374==    by 0x41A48EF: gme_open_file (gme.cpp:190)
==10374==    by 0x804A328: Music_Player::load_file(char const*, bool) (Music_Player.cpp:115) …
```
> Gb_Apu::Gb_Apu(): zero regs to avoid unitialized use in update_volume()

- Android.mk
- gme/Ym2612_Emu.h
- gme/Ym2612_GENS.cpp
- gme/Ym2612_MAME.cpp
- gme/Ym2612_Nuked.cpp
This helps with standalone makefiles, such as Android.mk
to include all those Ym2612* sources.  Also error out if
more than one VGM_YM2612_??? macro is defined.
> guard Ym2612* sources properly

- gme/Blip_Buffer.h
Fixes https://github.com/libgme/game-music-emu/issues/83
Patch proposed by Connor Clark (@connorjclark)
> Blip_Buffer.h: fixed build in c++20 mode.

- gme/CMakeLists.txt
-fwrapv is for gcc/clang only: fixes MSVC warnings.
> -fwrapv is for gcc/clang only:

- gme/Music_Emu.cpp
- gme/Sap_Emu.cpp
- gme/blargg_common.h
This fixes (silences) MSVC warnings C4291, C4805 and C4804.
See individual commit messages for details. Also see MSVC CI build
logs from master branch.
There is one warning left, C4146, occurring at 8 places. Don't know
what to do about them, don't know whether or not to do anything about
them.
```
Ay_Apu.cpp(302,22): warning C4146: unary minus operator applied to unsigned type, result still unsigned
Ay_Cpu.cpp(1044,11): warning C4146: unary minus operator applied to unsigned type, result still unsigned
Hes_Apu.cpp(109,28): warning C4146: unary minus operator applied to unsigned type, result still unsigned
Hes_Apu.cpp(112,50): warning C4146: unary minus operator applied to unsigned type, result still unsigned
Kss_Cpu.cpp(1082,11): warning C4146: unary minus operator applied to unsigned …
```
> MSVC warning fixes

- gme/Effects_Buffer.cpp
If we request more than 1 frame of multi-channel audio, the buffer will use a method that involves buffering 2 samples at a time for each voice, The placement of these samples, however, is incorrect.
Each frame should consist of 1 sample per voice (we actually duplicate the sample for the sake of stereo upmixing, so if `max_voices` equals 8, the frame will consist of 16 samples in total).
Rather than placing the voice's samples right next to each other, we should instead give the sample(s) for the 2nd frame an offset of `max_voices` (times 2 for upmixing), in order to account for the rest of the voices that the full frame will consist of. If we don't do this, the two frames will become interlaced.
Reasons why this has gone unnoticed:
- Multi-channel audio is a niche feature that hardly …
> Effects_Buffer: Offset samples by frame size for multi-channel buffering

- Android.mk
- CMakeLists.txt
- gme/CMakeLists.txt
- gme/Gme_File.cpp
- gme/Gme_File.h
- gme/Music_Emu.h
- gme/Spc_Emu.cpp
- gme/Spc_Emu.h
- gme/blargg_config.h
- gme/gme.cpp
- gme/gme.exports
- gme/gme.h
- player/Archive_Reader.cpp
- player/Archive_Reader.h
- player/CMakeLists.txt
- player/Music_Player.cpp
Rather than having RAR archives reserved specifically for SPC/RSN files, archives are now open to any single-track, or listable, file types. The archive's contents are scanned and an emulator is made for the first listable file type found.
Support has been implemented for RAR and ZIP. Both are optional, with RAR support being enabled with the presence of the UnRAR library, and ZIP support being enabled with the presence of the LibArchive library.
> Allow archive format for all single-track file types.

- gme/Blip_Buffer.cpp
- gme/Blip_Buffer.h
assert() may be disabled and you don't want to abort a whole process in case of a parsing issue. So check the offset from samples_avail(), that will return 0 (EOF) in case of a out of bounds read.
> Blip_Buffer: replace assert with a check

- gme/ext/emu2413.c
Fixes this warning from new gcc-14:
```
/tmp/libgme/gme/ext/emu2413.c: In function 'OPLL_new':
/tmp/libgme/gme/ext/emu2413.c:1003:35: warning: 'calloc' sizes specified with 'sizeof' in the earlier argument and not in the later argument [-Wcalloc-transposed-args]
1003 |   opll = (OPLL *) calloc (sizeof (OPLL), 1);
|                                   ^~~~
/tmp/libgme/gme/ext/emu2413.c:1003:35: note: earlier argument should specify number of elements, later size of each element
```
> fix -Wcalloc-transposed-args warning from gcc14

- gme/CMakeLists.txt
( See, e.g.: https://github.com/libsdl-org/SDL_image/issues/354 )
> cmake: -Wl,-undefined,error shouldn't be used on OpenBSD

- gme/Nsf_Emu.cpp
When compiling with `NSF_EMU_APU_ONLY`, the `set_voice_count` and `set_voice_names` functions don't get called, which makes the emulator fail to initialize properly and generated samples are all 0.
This small fix makes it so these 2 functions get called regardless if you're compiling with `NSF_EMU_APU_ONLY` or not.
> Fix silent NSF when compiling with NSF_EMU_APU_ONLY

- Android.mk
Not needed since commit bbbe9afb68eeae3c931f3183b91e2fc88847e37f
> Android.mk: remove 'exceptions' from LOCAL_CPP_FEATURES

- CMakeLists.txt
(I have been forgetting this...)
> cmake: add -fno-rtti and -fno-exceptions to the CXXFLAGS

- CMakeLists.txt
- demo/CMakeLists.txt
- gme/CMakeLists.txt
This is a small rework of the CMake build that allows building both shared and static versions of the library.
> CMake: Build both shared and static

- gme/CMakeLists.txt
MinGW already outputs different names for the static and the import libs
(Noticed at https://github.com/msys2/MINGW-packages/pull/23802)
> use -static suffix not in MinGW but MSVC builds

- gme/CMakeLists.txt
For Haiku headers are installed in /boot/system/develop/headers, which equals to CMAKE_INSTALL_INCLUDEDIR
> Fix header install path for non UNIX OS's

- gme/Music_Emu.cpp
Hi there!
I'm using libgme by way of [spct](https://codeberg.org/jneen/spct) and trying to render stems - each channel separately. I'm doing this by rendering with certain channels muted, but it seems like there was an oversight with regard to `ignore_silence` - Music_Emu.cpp will still end the track early if 6 seconds of silence is detected.
This patch allows for arbitrary runs of silence if `ignore_silence` has been set.
> don't detect track end if ignore_silence is on

- gme/Music_Emu.cpp
add explicit casts to avoid C4244 "conversion from 'double', possible loss of data" warnings
```
D:\a\game-music-emu\game-music-emu\gme\Music_Emu.cpp(236,25): warning C4244: 'return': conversion from 'double' to 'long', possible loss of data [D:\a\game-music-emu\game-music-emu\build\gme\gme_shared.vcxproj]
D:\a\game-music-emu\game-music-emu\gme\Music_Emu.cpp(254,17): warning C4244: 'initializing': conversion from 'double' to 'int32_t', possible loss of data [D:\a\game-music-emu\game-music-emu\build\gme\gme_shared.vcxproj]
D:\a\game-music-emu\game-music-emu\gme\Music_Emu.cpp(257,22): warning C4244: 'initializing': conversion from 'double' to 'int', possible loss of data [D:\a\game-music-emu\game-music-emu\build\gme\gme_shared.vcxproj] …
```
> Silence some MSVC warnings

- gme/Kss_Emu.cpp
Sega Master System is equipped with an SN76489 PSG chip, the Mega Drive additionally includes an YM2612
inspired by kode54's code https://github.com/kode54/Game_Music_Emu/blob/master/gme/Kss_Emu.cpp
> kss: distinguish between Sega systems
